export const IMAGES_LOADED = 'IMAGES_LOADED';
export const IMAGE_DETAILS_LOADED = 'IMAGE_DETAILS_LOADED';

export const GET_IMAGES_SAGA_REQUEST = 'GET_IMAGES_SAGA_REQUEST';
export const GET_IMAGE_SAGA_REQUEST = 'GET_IMAGE_SAGA_REQUEST';

export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';
